
CREATE DATABASE AGEX_DASHBOARD

USE AGEX_DASHBOARD

CREATE TABLE	agex_user
(
	[USER_ID]		VARCHAR(32) NOT NULL,
	USER_PASSWORD	VARCHAR(50),
	ATTEMPTS		INT,
	LAST_LOGIN		DATETIME,
	CREATE_DATETIME	DATETIME,
	UPDATE_DATETIME	DATETIME,
	STATUS			VARCHAR(3)
)

CREATE TABLE	agex_activity 
(
	ACTIVITY_ID		VARCHAR(32) NOT NULL,
	JSON_REQUEST	VARCHAR(MAX),
	JSON_RESPONSE	VARCHAR(MAX),
	[TYPE]			VARCHAR(15),
	STATUSCODE		VARCHAR(3),
	CREATE_DATETIME	DATETIME,
	UPDATE_DATETIME	DATETIME
);

CREATE TABLE	agex_employee
(
	EMPLOYEE_ID			INT NOT NULL IDENTITY,
	EMPLOYEE_NAME		VARCHAR(50),
	EMPLOYEE_LAST_NAME	VARCHAR(50),
	AGE					INT,
	DATE_BIRTHDAY		VARCHAR(10),
	GENDER				VARCHAR(1),
	EMPLOYEE_DPI		VARCHAR(13),
	NIT					VARCHAR(15),
	IGSS				VARCHAR(13),
	IRTRA				VARCHAR(16),
	PASSPORT			VARCHAR(13),
	WORKSTATION_ID		INT,
	CREATE_DATETIME		DATETIME,
	UPDATE_DATETIME		DATETIME,
	STATUS				VARCHAR(3)
);

CREATE TABLE	agex_employee_workstation
(
	WORKSTATION_ID			INT NOT NULL IDENTITY,
	SALARY_ID				INT,
	NAME_WORKSTATION		VARCHAR(255),
	CREATE_DATETIME			DATETIME,
	UPDATE_DATETIME			DATETIME,
	STATUS					VARCHAR(3)
)

CREATE TABLE	agex_employee_address
(
	ADDRESS_ID		INT NOT NULL IDENTITY,
	EMPLOYEE_DPI		VARCHAR(13),
	ADDRESS_LINE_1	VARCHAR(255),
	ADDRESS_LINE_2	VARCHAR(255),
	COUNTRY_ID		INT,
	STATE_ID		INT,
	CREATE_DATETIME	DATETIME,
	UPDATE_DATETIME	DATETIME,
	STATUS			VARCHAR(3)
)

CREATE TABLE	agex_employee_email
(
	EMAIL_ID	INT NOT NULL IDENTITY,
	EMPLOYEE_DPI		VARCHAR(13),
	EMAIL		VARCHAR(100),
	CREATE_DATETIME	DATETIME,
	UPDATE_DATETIME DATETIME,
	STATUS		VARCHAR(3)
)


CREATE TABLE	agex_country
(
	COUNTRY_ID		INT NOT NULL IDENTITY,
	COUNTRY_NAME	VARCHAR(100),
	CREATE_DATETIME	DATETIME,
	UPDATE_DATETIME	DATETIME,
	STATUS			VARCHAR(3)
)


CREATE TABLE	agex_state
(
	STATE_ID		INT NOT NULL IDENTITY,
	STATE_NAME		VARCHAR(100),
	CREATE_DATETIME	DATETIME,
	UPDATE_DATETIME	DATETIME,
	STATUS			VARCHAR(3)
)

CREATE TABLE	agex_employee_phone
(
	PHONE_ID			INT NOT NULL IDENTITY,
	EMPLOYEE_DPI		VARCHAR(13),
	EMPLOYEE_PHONE		VARCHAR(15),
	CREATE_DATETIME		DATETIME,
	UPDATE_DATETIME		DATETIME,
	STATUS				VARCHAR(2)
)


CREATE TABLE	agex_employee_salary
(
	SALARY_ID			INT NOT NULL IDENTITY,
	SALARY_AMOUNT		FLOAT,
	CURRENCY_ID			VARCHAR(3),
	CREATE_DATETIME		DATETIME,
	UPDATE_DATETIME		DATETIME,
	STATUS				VARCHAR(3)
)


CREATE TABLE	agex_orders
(
	ORDER_ID		INT NOT NULL IDENTITY,
	DESCRIPTION		VARCHAR(MAX),
	WEIGHT_ORDER	FLOAT,
	NUMBER_PRODUCTS	INT,
	AMOUNT_TOTAL	FLOAT,
	CREATE_DATETIME DATETIME,
	UPDATE_DATETIME DATETIME,
	STATUS			VARCHAR(20)
)




